version: "3.7"

services:
  tester:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    user: tester
    working_dir: /home/tester
    tty: true
    command: bash
    volumes:
      - ../workspace:/home/tester/workspace

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wscraper
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
        - storage:/var/lib/mysql

volumes:
  storage:
      driver: local
